/**
This file is part of CalinRadoni/light-effects component
(https://github.com/CalinRadoni/light-effects)
Copyright (C) 2021 by Calin Radoni

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef color_hsv_H
#define color_hsv_H

#include <stddef.h>
#include <stdint.h>

class ColorWRGB;

class ColorHSV
{
public:
    uint16_t h;     // 0 .. 1529 (See Adafruit_NeoPixel::ColorHSV if you need details)
    uint8_t s, v;

    ColorHSV(void) : h(0), s(0), v(0) { }

    ColorHSV(uint16_t ih, uint8_t is, uint8_t iv) : h(ih), s(is), v(iv) {}

    ColorHSV(uint32_t val);

    /**
     * @brief HSV to RGB, for hue in [0..1529]
     *
     * @warning HUE should be limited to [0..1529]
     *          The max number of colors generated by this function is 6 * 255 = 1530
     *
     * Hue and colors (for s = 0xFF and v = 0xFF):
     *      0 = FF0000
     *    255 = FFFF00
     *    510 = 00FF00
     *       ...
     *   1529 = FF0001
     * > 1290 = 000000
     *
     * Based on algorithm from https://en.wikipedia.org/wiki/HSL_and_HSV
     * Similar to Adafruit_NeoPixel::ColorHSV (https://github.com/adafruit/Adafruit_NeoPixel/blob/master/Adafruit_NeoPixel.cpp)
     */
    void ToRGB_raw(ColorWRGB&);

    /**
     * @brief HSV to RGB, for hue in [0..764]
     *
     * @warning HUE should be limited to [0..764]
     *          The max number of colors generated by this function is 3 * 255 = 765
     *
     * Is like the ToRGB_raw function but with "constant intensity"
     * Similar to hsv2rgb_raw_C from FastLED (https://github.com/FastLED/FastLED)
     */
    void ToRGB_raw_cl(ColorWRGB&);

protected:
    void ApplySV(uint8_t, uint8_t, uint8_t, ColorWRGB&);
};

#endif
